#!/bin/bash

source lib/config.sh

[[ -d sensitive ]] && rm -r sensitive

mkdir -p sensitive

openssl rand -base64 48 | md5sum | awk '{print $1}' > sensitive/pg_pass
ssh-keygen -q -t rsa -N "" -C "key for root access" -f sensitive/id_root
ssh-keygen -q -t rsa -N "" -C "key for user access" -f sensitive/id_user

mkdir -p $data_folder/pg
mkdir -p $data_folder/src
cp files/install.sh $data_folder/src/


